apiVersion: sops.peakscale.ch/v1alpha1
kind: SopsSecret
metadata:
    name: example-secret
spec:
    secrets:
        - name: my-secret-name-1
          labels:
            label1: value1
          stringData:
            data-name0: ENC[AES256_GCM,data:m/VG12vSPVP4NS0=,iv:tB3zBrRdtkaB9SdyWfOH5/BT0fH6QMRLtch7aFOLI/E=,tag:y+o4BuN5bRMdI0wCeA01Rw==,type:str]
          data:
            data-name1: ENC[AES256_GCM,data:MbgjZ1pvDgofEJh/p5SQbA==,iv:2e/DZXxQCDNfHt1zxCEAXFeVgtbCLdqDx4Y0JjfJH4g=,tag:s5D5s8CuWw9qHYwAy7PJPA==,type:str]
        - name: jenkins-secret
          labels:
            jenkins.io/credentials-type: usernamePassword
          annotations:
            jenkins.io/credentials-description: credentials from Kubernetes
          stringData:
            username: ENC[AES256_GCM,data:CSZ8A/b9d21tbA==,iv:9zpDqBp5MIVqFrKKGGiSQg0InlSw5O/shv86LftPzg0=,tag:E1So8yXTjiu4KwwNXztXsA==,type:str]
            password: ENC[AES256_GCM,data:3S4sOAS2bEQ=,iv:RNDuXJpVtBo8NiZr4/g6Zjjp9Gq+e9yF3tukRTA7leU=,tag:F5aAIw6KNMv+GJv2XEgYBw==,type:str]
        - name: docker-login
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:ikWS88qwtt2i+sFbT1QtkLbV3bzloAwKskDLd3ypJVglVwLVmm+0CJ1VnyemAHcLRM56M/k0/AM76gz0HBQ+RnAKuq9IqJc8My6gOLv35TDX39a+U5iH+5cvtgCa1k7Q4CjGrv2b4PrcAtWaG+esWsoFww6v4/WBcaZWsIvfzg==,iv:Re+0yieLq0dW6V35Rt3rrliWWX07voRCLUawwZ7FoOo=,tag:Vkkaro72aXwNj5BYWyfkFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-04T01:38:26Z"
    mac: ENC[AES256_GCM,data:CjgzOe3YFaxCj9PkKMceIpQJTgNcth625xMtKptsnNMMg7MR9VdSOORqFaw4lDXUXdGs9QvPNgTz7YKX3RwDMZTLrUnmwUm9YLpOe3/rRyY/E1pKgqr43W0E8pNnWtjQlmgbRdLd4yNDnvwLRnL66aoa9WvHqNr4CoQXtDhAf2M=,iv:6ftsNfk3DpHovrqBs4h7vbP0UCqnYI7cYrbXJlwQkHg=,tag:2hgv8q5fNxe61Maxy7uzKg==,type:str]
    pgp:
        - created_at: "2025-02-04T01:38:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4Zyy+rN8BAMARAAgTsH6dIWYQVGsGz40KHEngftxfRssqeQmSfH1IqWIUpi
            2bBqyI3d4WGFzv3WhZNQUHL3tGclTm/zyrKfaJWTuB2mAkaEiExM/Ee8ArKLJPng
            Z/xysuJvYDqVgKe+Ul/VMb7N4y0MniUjjVpR52C5a6z3WAknXO3ai/1WGrD1bLiE
            lZ3bY8k17bIpct/y1NR0X2EaxvQKyS/SE5/eKrj7W32ryrySKHbXcizGMaKle35x
            kalyETfOxYgyfNc5sBrsOQlMY8emFnMmfNuOOyON7Qde14s91YU1Vx49u5wl7UlD
            uKaGY9KuWdyXnpHYX7XavHgPHEbhtnySIcwGbxJs9KrzQoL47+AUUT9AaZM3bsep
            sddP/KM0q9P8aYO61aYViI42KqLJBfsvb5IN+7Qf5/7iO8SBEds6tH52gJ34nBMO
            YB7GGbkfyjb5VD1bM5Ys5EP0sXnl/kTreWd1ZDEF6iWQMXzQg9DMVPkTdy7HN+4h
            9Siha4EX9pLpreCrh1xq3DO8h6rTvER5d/kEQMUFRh8AxnlqXCgNfNkqkM5vSE5r
            E7Zg8CcxT5eSzYiRCO+rw5fAPJrSJ7PS+RGQPOBiQZEECewsSgRRwaH9LWeC9OGJ
            iqc+kHU3t/qc6uathtIf3lappyn53DQGrCkupxBxSo8pq9ibQ9r41Z0WSnZgXZnU
            ZgEJAhAXUFslMGbzR3lynTL8SSQ8UKXpq1RAylon1E4CSkKnKBW9JcXVPHvlDqH7
            p/+Ht/2+q/GX13w0hIPwgt+AWZm/iUEZLn8Mn6B3JZpQxEBq1fMziVj7RZ5MsjNV
            6WlhMCHj3w==
            =3iNP
            -----END PGP MESSAGE-----
          fp: CE411B68660C33B0F83A4EBD56FDA28155A45CB1
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
